apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kutti-provisioner
  labels:
    app.kubernetes.io/name: provisioner-localvolume
    app.kubernetes.io/part-of: kutti
rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - persistentvolumes/status
    verbs:
    - update
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims/status
    verbs:
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    verbs:
    - create
    - delete
    - get
    - update
    - list
    - watch
  - apiGroups:
    - "coordination.k8s.io"
    resources:
    - leases
    verbs:
    - create
    - delete
    - get
    - update
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kutti-provisioner
  labels:
    app.kubernetes.io/name: provisioner-localvolume
    app.kubernetes.io/part-of: kutti
subjects:
  - kind: ServiceAccount
    namespace: kutti-provisioner
    name: kutti-provisioner
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: kutti-provisioner
  apiGroup: rbac.authorization.k8s.io
