apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net
  labels:
    day: day5
    sample: multinetworks
spec:
  config: |- 
    {
      "cniVersion": "0.3.1",
      "name": "bridge-net",
      "type": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
                    [
                      {
                        "subnet": "10.10.0.0/16",
                        "rangeStart": "10.10.1.20",
                        "rangeEnd": "10.10.3.50",
                        "gateway": "10.10.0.254"
                      },
                      {
                        "subnet": "172.16.5.0/24"
                      }
                    ],
                    [
                      {
                        "subnet": "3ffe:ffff:0:01ff::/64",
                        "rangeStart": "3ffe:ffff:0:01ff::0010",
                        "rangeEnd": "3ffe:ffff:0:01ff::0020"
                      }
                    ]
          ],
          "routes": [
                    { "dst": "0.0.0.0/0" },
                    { "dst": "192.168.0.0/16", "gw": "10.10.5.1" },
                    { "dst": "3ffe:ffff:0:01ff::1/64" }
          ]
      },
      "bridge": "ucni0"
    }